# Generated by Django 5.2.6 on 2026-03-23 20:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_webhookendpointmodel_webhookdeliverymodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDeliveryAttemptModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('request_headers', models.JSONField(default=dict)),
                ('request_body', models.JSONField(default=dict)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'finances_webhooks_delivery_attempts',
            },
        ),
        migrations.RemoveField(
            model_name='webhookdeliverymodel',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='webhookdeliverymodel',
            name='response_status',
        ),
        migrations.AddField(
            model_name='webhookdeliverymodel',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookdeliverymodel',
            name='event_id',
            field=models.UUIDField(default='0bf5db18-f2dd-4a18-9095-9a30ae25235e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webhookdeliverymodel',
            name='event_type',
            field=models.CharField(choices=[('transaction.create', 'Transaction Created')], default='transactions.create', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webhookdeliverymodel',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookdeliverymodel',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('wip', 'In Progress'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='initiated', max_length=64),
        ),
        migrations.AlterField(
            model_name='webhookdeliverymodel',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='finances.webhookendpointmodel'),
        ),
        migrations.AlterField(
            model_name='webhookendpointmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverymodel',
            index=models.Index(fields=['endpoint'], name='finances_we_endpoin_18083d_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverymodel',
            index=models.Index(fields=['status'], name='finances_we_status_2b6d97_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverymodel',
            index=models.Index(fields=['event_id'], name='finances_we_event_i_371a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverymodel',
            index=models.Index(fields=['event_id', 'endpoint'], name='finances_we_event_i_dee1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverymodel',
            index=models.Index(fields=['event_type'], name='finances_we_event_t_9e3cfc_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookdeliverymodel',
            constraint=models.UniqueConstraint(fields=('endpoint', 'event_id'), name='unique_webhook_delivery_endpoint_event'),
        ),
        migrations.AddField(
            model_name='webhookdeliveryattemptmodel',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='finances.webhookdeliverymodel'),
        ),
        migrations.AddConstraint(
            model_name='webhookdeliveryattemptmodel',
            constraint=models.UniqueConstraint(fields=('delivery', 'attempt_number'), name='unique_webhook_attempt_delivery_attempt'),
        ),
    ]
