# Generated by Django 5.2.6 on 2026-03-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_webhookdeliveryattemptmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdeliverymodel',
            name='event_type',
            field=models.CharField(choices=[('transaction.created', 'Transaction Created')], max_length=50),
        ),
        migrations.AlterField(
            model_name='webhookdeliverymodel',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('retry_scheduled', 'Retry Scheduled'), ('delivered', 'Delivered'), ('failed_permanently', 'Failed Permanently')], default='initiated', max_length=64),
        ),
    ]
