# Generated by Django 5.2.6 on 2026-04-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_notificationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='received_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
