# Generated by Django 5.2.6 on 2026-04-04 23:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_notificationmodel_received_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookPayloadModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'finances_webhook_payloads',
            },
        ),
        migrations.AlterField(
            model_name='webhookdeliverymodel',
            name='status',
            field=models.CharField(choices=[('WebhookDeliveryStatus.IN_PROGRESS', 'Initiated'), ('WebhookDeliveryStatus.RETRY_SCHEDULED', 'Retry Scheduled'), ('WebhookDeliveryStatus.SUCCESS', 'Delivered'), ('WebhookDeliveryStatus.FAILED', 'Failed Permanently')], default='WebhookDeliveryStatus.IN_PROGRESS', max_length=64),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverymodel',
            index=models.Index(fields=['status', 'next_retry_at'], name='finances_we_status_81c4cd_idx'),
        ),
        migrations.AddField(
            model_name='webhookpayloadmodel',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finances.webhookdeliverymodel'),
        ),
        migrations.AddIndex(
            model_name='webhookpayloadmodel',
            index=models.Index(fields=['delivery', 'hash'], name='finances_we_deliver_1ed9e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookpayloadmodel',
            constraint=models.UniqueConstraint(fields=('delivery', 'hash'), name='unique_webhook_payload_delivery'),
        ),
    ]
