# Generated by Django 5.2.6 on 2026-04-18 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_webhookpayloadmodel_headers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletmodel',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='walletmodel',
            name='credit',
        ),
        migrations.AlterField(
            model_name='webhookdeliverymodel',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='webhookdeliverymodel',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Initiated'), ('retry_scheduled', 'Retry Scheduled'), ('success', 'Delivered'), ('failed', 'Failed Permanently')], default='retry_scheduled', max_length=64),
        ),
        migrations.DeleteModel(
            name='TransactionModel',
        ),
    ]
