apiVersion: apps/v1
kind: Deployment
metadata:
  name: uvicorn-django-deployment
  labels:
    app: uvicorn-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: django-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django-server
    spec:
      serviceAccountName: django-sa
      containers:
      - name: django
        image: ghcr.io/isoldpower/power-finance-backend:1.0.0
        ports:
        - containerPort: 8000
        # Health Probes
        startupProbe:
          httpGet:
            path: /health/startup
            port: 8000
          failureThreshold: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 15
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        # Env variables mapping
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: power-finance
              key: debug
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: power-finance
              key: app-name
        - name: API_VERSION
          valueFrom:
            configMapKeyRef:
              name: power-finance
              key: api-version
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: power-finance
              key: database-host
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: power-finance
              key: database-port
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: power-finance
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: power-finance
              key: redis-port
        - name: REDIS_CELERY_DATABASE_INDEX
          valueFrom:
            configMapKeyRef:
              name: power-finance
              key: redis-celery-database-index
        - name: RABBIT_MQ_HOST
          valueFrom:
            configMapKeyRef:
              name: power-finance
              key: rabbitmq-host
        - name: RABBIT_MQ_PORT
          valueFrom:
            configMapKeyRef:
              name: power-finance
              key: rabbitmq-port
        - name: RABBIT_MQ_MANAGEMENT_PORT
          valueFrom:
            configMapKeyRef:
              name: power-finance
              key: rabbitmq-management-port
        - name: CLERK_API_URL
          valueFrom:
            configMapKeyRef:
              name: power-finance
              key: clerk-api-url
        - name: CLERK_CACHE_KEY
          valueFrom:
            configMapKeyRef:
              name: power-finance
              key: clerk-cache-key
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: .database-user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: .database-password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: .redis-password
        - name: RABBIT_MQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: .rabbit-mq-user
        - name: RABBIT_MQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: .rabbit-mq-password
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: .secret-key
        - name: CLERK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: .clerk-secret-key
