# Generated by Django 5.2.14 on 2026-05-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionReadModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('wallet_id', models.UUIDField()),
                ('user_id', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency_code', models.CharField(blank=True, default='', max_length=8)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'read_transactions',
                'indexes': [models.Index(fields=['wallet_id', '-occurred_at'], include=('amount', 'currency_code', 'user_id'), name='rt_wallet_occurred_idx'), models.Index(fields=['user_id', '-occurred_at'], include=('amount', 'currency_code', 'wallet_id'), name='rt_user_occurred_idx'), models.Index(fields=['wallet_id', '-created_at'], name='rt_wallet_created_idx'), models.Index(fields=['user_id', 'currency_code'], name='rt_user_currency_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletReadModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('currency_code', models.CharField(max_length=8)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'read_wallets',
                'indexes': [models.Index(fields=['user_id', '-created_at'], include=('title', 'currency_code', 'balance'), name='rw_user_created_idx'), models.Index(fields=['user_id', 'currency_code'], name='rw_user_currency_idx'), models.Index(fields=['currency_code'], name='rw_currency_idx')],
            },
        ),
    ]
