# Generated by Django 5.2.14 on 2026-06-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_read_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedOutboxSeq',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('applied_seq', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'read_applied_outbox_seq',
            },
        ),
    ]
