# Generated by Django 5.2.14 on 2026-06-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_read_core', '0002_appliedoutboxseq'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationReadModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('short', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'read_notifications',
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='rn_user_created_idx'), models.Index(fields=['user_id', 'is_read'], name='rn_user_unread_idx')],
            },
        ),
    ]
