# Generated by Django 5.2.14 on 2026-06-13 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_read_core', '0003_notificationreadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookReadModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'read_webhooks',
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='rwh_user_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscriptionReadModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('event_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='data_read_core.webhookreadmodel')),
            ],
            options={
                'db_table': 'read_webhook_subscriptions',
                'indexes': [models.Index(fields=['webhook', 'created_at'], name='rwhs_webhook_created_idx')],
            },
        ),
    ]
