# Generated by Django 5.2.14 on 2026-08-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_read_core', '0005_esappliedoutboxseq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyReadModel',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('numeric', models.CharField(max_length=3)),
                ('digits', models.IntegerField()),
            ],
            options={
                'db_table': 'read_currencies',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveIndex(
            model_name='notificationreadmodel',
            name='rn_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='walletreadmodel',
            name='rw_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookreadmodel',
            name='rwh_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhooksubscriptionreadmodel',
            name='rwhs_webhook_created_idx',
        ),
        migrations.AddIndex(
            model_name='notificationreadmodel',
            index=models.Index(fields=['user_id', '-created_at', '-id'], name='rn_user_keyset_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionreadmodel',
            index=models.Index(fields=['user_id', '-created_at', '-id'], include=('amount', 'currency_code', 'wallet_id'), name='rt_user_keyset_idx'),
        ),
        migrations.AddIndex(
            model_name='walletreadmodel',
            index=models.Index(fields=['user_id', '-created_at', '-id'], include=('title', 'currency_code', 'balance'), name='rw_user_keyset_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookreadmodel',
            index=models.Index(fields=['user_id', '-created_at', '-id'], name='rwh_user_keyset_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooksubscriptionreadmodel',
            index=models.Index(fields=['webhook', '-created_at', '-id'], name='rwhs_webhook_keyset_idx'),
        ),
    ]
