# Generated by Django 5.2.14 on 2026-08-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_read_core', '0008_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletreadmodel',
            name='category',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='walletreadmodel',
            name='color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='walletreadmodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletreadmodel',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='walletreadmodel',
            name='zero_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddIndex(
            model_name='walletreadmodel',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['user_id', '-favorite', '-created_at', '-id'], include=('title', 'currency_code', 'balance', 'zero_balance'), name='rw_user_favorite_idx'),
        ),
    ]
