# Generated by Django 5.2.14 on 2026-08-21 21:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_read_core', '0009_walletreadmodel_category_walletreadmodel_color_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transactionreadmodel',
            name='rt_wallet_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='transactionreadmodel',
            name='rt_user_keyset_idx',
        ),
        migrations.AddField(
            model_name='transactionreadmodel',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionreadmodel',
            name='chain_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionreadmodel',
            name='chain_sort',
            field=models.UUIDField(default=uuid.UUID('ffffffff-ffff-ffff-ffff-ffffffffffff')),
        ),
        migrations.AddField(
            model_name='transactionreadmodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionreadmodel',
            name='evidence_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='transactionreadmodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transactionreadmodel',
            name='origin',
            field=models.CharField(blank=True, default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='transactionreadmodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionreadmodel',
            name='wallet_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='transactionreadmodel',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['user_id', '-created_at', 'chain_sort', '-id'], include=('amount', 'currency_code', 'wallet_id', 'wallet_name', 'name'), name='rt_user_chain_keyset_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionreadmodel',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['wallet_id', '-created_at'], name='rt_wallet_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionreadmodel',
            index=models.Index(fields=['chain_id'], name='rt_chain_idx'),
        ),
    ]
