# Generated by Django 5.2.14 on 2026-08-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_read_core', '0010_remove_transactionreadmodel_rt_wallet_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionreadmodel',
            name='container_kind',
            field=models.CharField(default='wallet', max_length=8),
        ),
        migrations.CreateModel(
            name='GoalReadModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('currency_code', models.CharField(max_length=8)),
                ('target', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('finish_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'read_goals',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['user_id', '-created_at', '-id'], include=('title', 'currency_code', 'target', 'progress'), name='rg_user_keyset_idx')],
            },
        ),
    ]
