# Generated by Django 5.2.14 on 2026-08-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_read_core', '0011_transactionreadmodel_container_kind_goalreadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDispatchReadModel',
            fields=[
                ('transaction_id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('dispatch_id', models.UUIDField()),
                ('balanced', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('backend', models.CharField(blank=True, default='', max_length=32)),
                ('created_count', models.IntegerField(default=0)),
                ('deleted_count', models.IntegerField(default=0)),
                ('dispatched_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'read_account_dispatches',
                'indexes': [models.Index(fields=['user_id'], name='rad_user_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountPostingReadModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('account_id', models.UUIDField()),
                ('transaction_id', models.UUIDField()),
                ('dispatch_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('debit', models.BooleanField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency_code', models.CharField(blank=True, default='', max_length=8)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'read_account_postings',
                'indexes': [models.Index(fields=['account_id', '-created_at', '-id'], include=('amount', 'currency_code', 'debit', 'title'), name='rap_account_keyset_idx'), models.Index(fields=['transaction_id', 'position'], name='rap_transaction_idx'), models.Index(fields=['user_id'], name='rap_user_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountReadModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('group', models.CharField(blank=True, default='', max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'read_accounts',
                'indexes': [models.Index(fields=['user_id', 'group', 'name'], include=('balance',), name='ra_user_chart_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'group', 'name'), name='ra_identity')],
            },
        ),
    ]
