# Generated by Django 5.2.14 on 2026-09-01 06:29

import data_read_core.shared.postgres_orm.action
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_read_core', '0014_notification_target_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionReadModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('source', models.CharField(max_length=16)),
                ('kind', models.CharField(max_length=64)),
                ('severity', models.CharField(default=data_read_core.shared.postgres_orm.action.ActionSeverity['INFO'], max_length=16)),
                ('severity_rank', models.IntegerField(default=1)),
                ('status', models.CharField(default=data_read_core.shared.postgres_orm.action.ActionStatus['PENDING'], max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True, default='')),
                ('subject_type', models.CharField(blank=True, default='', max_length=32)),
                ('subject_id', models.CharField(blank=True, default='', max_length=64)),
                ('money_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('money_currency', models.CharField(blank=True, default='', max_length=8)),
                ('group_key', models.CharField(blank=True, default='', max_length=128)),
                ('occurrences', models.IntegerField(default=1)),
                ('last_seen_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolutions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'read_actions',
                'indexes': [models.Index(fields=['user_id', 'status', '-severity_rank', '-created_at', '-id'], include=('kind', 'title', 'severity'), name='ra_queue_keyset_idx'), models.Index(fields=['user_id', 'source'], name='ra_user_source_idx')],
            },
        ),
    ]
