# Generated by Django 5.2.14 on 2026-09-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_read_core', '0015_actionreadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationReadModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('trigger_type', models.CharField(max_length=16)),
                ('trigger_event', models.CharField(blank=True, default='', max_length=32)),
                ('trigger_schedule', models.CharField(blank=True, default='', max_length=16)),
                ('filter_body', models.JSONField(blank=True, null=True)),
                ('effects', models.JSONField(default=list)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('runs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'read_automations',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['user_id', '-created_at', '-id'], include=('name', 'enabled'), name='rau_user_keyset_idx'), models.Index(fields=['user_id', 'enabled'], name='rau_user_enabled_idx')],
            },
        ),
    ]
