# Generated by Django 5.2.14 on 2026-09-08 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_read_core', '0016_automationreadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaConsumedEvent',
            fields=[
                ('pk', models.CompositePrimaryKey('consumer_group', 'event_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('consumer_group', models.TextField()),
                ('event_id', models.TextField()),
                ('consumed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'kafka_consumed_events',
                'indexes': [models.Index(fields=['consumed_at'], name='kafka_consumed_at_idx')],
            },
        ),
    ]
