# Custom postgresql.conf for write-side Postgres.

# pull the image-defined Postgres defaults. Everything that goes after are overrides.
include_if_exists = '/var/lib/postgresql/data/pgdata/postgresql.conf'

# publish all logical events to WAL to be consumed by Debezium.
wal_level = logical
# adjust the amount of WAL senders for data replication and scalability purposes.
max_wal_senders = 4
# adjust the amount of postgres replicas to not flood Debezium too much.
max_replication_slots = 4
# bounds the WAL that an idle/stalled replication
max_slot_wal_keep_size = '2GB'
