"""Generate __init__.py for the Python kafka_messages package.

Called by generate.sh after protoc has emitted the *_pb2.py / *_pb2.pyi
files. Introspects each *_pb2 module's FileDescriptor for top-level
messages and enums, then writes a single __init__.py that re-exports
them — so downstream code can keep doing `from kafka_messages import
TransactionCreated` regardless of which proto file defines what.

The script is intentionally small and dependency-free (stdlib only) so
it works from anywhere `python -m grpc_tools.protoc` works.
"""

from __future__ import annotations

import importlib
import sys
from pathlib import Path


def collect_exports(package_dir: Path, package_import_name: str) -> dict[str, list[str]]:
    """Return {pb_module_stem: [exported names]} for every *_pb2.py."""
    package_parent = package_dir.parent
    if str(package_parent) not in sys.path:
        sys.path.insert(0, str(package_parent))

    exports: dict[str, list[str]] = {}
    for pb_file in sorted(package_dir.glob("*_pb2.py")):
        module_name = f"{package_import_name}.{pb_file.stem}"
        module = importlib.import_module(module_name)
        file_descriptor = module.DESCRIPTOR
        message_names = list(file_descriptor.message_types_by_name.keys())
        enum_names = list(file_descriptor.enum_types_by_name.keys())
        names = sorted(message_names + enum_names)
        if names:
            exports[pb_file.stem] = names
    return exports


def render_init(exports: dict[str, list[str]]) -> str:
    """Format the __init__.py source as a string."""
    lines: list[str] = [
        '"""Auto-generated public API for cross-service Kafka events.',
        "",
        "Do not edit — regenerated by ../../generate.sh from protobufs/.",
        '"""',
        "",
    ]

    all_exported_names: list[str] = []
    for pb_stem in sorted(exports):
        names = exports[pb_stem]
        all_exported_names.extend(names)
        if len(names) == 1:
            lines.append(f"from .{pb_stem} import {names[0]}")
        else:
            lines.append(f"from .{pb_stem} import (")
            for name in names:
                lines.append(f"    {name},")
            lines.append(")")

    lines.extend(
        [
            "",
            "__all__ = [",
            *(f'    "{name}",' for name in sorted(set(all_exported_names))),
            "]",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("usage: _gen_init.py <path-to-kafka_messages-package-dir>")
    package_dir = Path(sys.argv[1]).resolve()
    package_import_name = package_dir.name

    exports = collect_exports(package_dir, package_import_name)
    rendered = render_init(exports)

    (package_dir / "__init__.py").write_text(rendered)


if __name__ == "__main__":
    main()
