#!/usr/bin/env bash
set -euo pipefail

sandbox_name="${1:?usage: generate_sandbox_env.sh <sandbox-name> <service> <dev-host> <output-file>}"
service_name="${2:?missing service}"
dev_host="${3:?missing dev host}"
output_file="${4:?missing output file}"

kafka_port="${KAFKA_EXTERNAL_PORT:-19092}"
write_database_port="${WRITE_DATABASE_EXTERNAL_PORT:-5433}"
read_database_port="${READ_DATABASE_EXTERNAL_PORT:-5434}"
ai_database_port="${AI_DATABASE_EXTERNAL_PORT:-5436}"
webhook_database_port="${WEBHOOK_DATABASE_EXTERNAL_PORT:-5437}"
write_redis_port="${WRITE_REDIS_EXTERNAL_PORT:-6383}"
read_redis_port="${READ_REDIS_EXTERNAL_PORT:-6384}"
immudb_port="${IMMUDB_EXTERNAL_PORT:-3322}"
elasticsearch_hosts="${ELASTICSEARCH_HOSTS:-https://${dev_host}:9200}"

case "$service_name" in
    write-service|write-*)
        database_port="$write_database_port"
        database_name="${WRITE_DATABASE_NAME:-power_finance_write}"
        redis_port="$write_redis_port"
        ;;
    read-service|read-*)
        database_port="$read_database_port"
        database_name="${READ_DATABASE_NAME:-power_finance_read}"
        redis_port="$read_redis_port"
        ;;
    ai-service|ai-*)
        database_port="$ai_database_port"
        database_name="${AI_DATABASE_NAME:-power_finance_ai}"
        redis_port="$read_redis_port"
        ;;
    webhook-service)
        database_port="$webhook_database_port"
        database_name="${WEBHOOK_DATABASE_NAME:-power_finance_webhook}"
        redis_port="$read_redis_port"
        ;;
    *)
        database_port="$write_database_port"
        database_name="${WRITE_DATABASE_NAME:-power_finance_write}"
        redis_port="$write_redis_port"
        ;;
esac

mkdir -p "$(dirname "$output_file")"
cat > "$output_file" <<ENVEOF
# Generated by \`make sandbox-env NAME=$sandbox_name SERVICE=$service_name\`.
# Source this before running $service_name natively against the shared baseline.
# Every endpoint points at the dev host; nothing here starts infrastructure.
SANDBOX_ID=$sandbox_name

KAFKA_BOOTSTRAP_SERVERS=${dev_host}:${kafka_port}

DATABASE_HOST=$dev_host
DATABASE_PORT=$database_port
DATABASE_NAME=$database_name
DATABASE_USER=${DATABASE_USER:-postgres}
DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}

REDIS_HOST=$dev_host
REDIS_PORT=$redis_port

IMMUDB_HOST=$dev_host
IMMUDB_PORT=$immudb_port
IMMUDB_USER=${IMMUDB_USER:-immudb}
IMMUDB_PASSWORD=${IMMUDB_PASSWORD:-immudb}

ELASTICSEARCH_HOSTS=$elasticsearch_hosts
ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD:-changeme}
ELASTICSEARCH_VERIFY_CERTS=${ELASTICSEARCH_VERIFY_CERTS:-false}

OTEL_EXPORTER_OTLP_ENDPOINT=http://${dev_host}:4317
OTEL_SERVICE_NAME=$service_name
OTEL_DEPLOYMENT_ENVIRONMENT=sandbox
ENVEOF

echo "$output_file"
