#!/usr/bin/env bash
set -euo pipefail

sandbox_name="${1:?usage: generate_sandbox_env.sh <sandbox-name> <service> <dev-host> <output-file>}"
service_name="${2:?missing service}"
dev_host="${3:?missing dev host}"
output_file="${4:?missing output file}"

kafka_port="${KAFKA_EXTERNAL_PORT:-19092}"
write_database_port="${WRITE_DATABASE_EXTERNAL_PORT:-5433}"
read_database_port="${READ_DATABASE_EXTERNAL_PORT:-5434}"
ai_database_port="${AI_DATABASE_EXTERNAL_PORT:-5436}"
webhook_database_port="${WEBHOOK_DATABASE_EXTERNAL_PORT:-5437}"
write_redis_port="${WRITE_REDIS_EXTERNAL_PORT:-6383}"
read_redis_port="${READ_REDIS_EXTERNAL_PORT:-6384}"
immudb_port="${IMMUDB_EXTERNAL_PORT:-3322}"
elasticsearch_hosts="${ELASTICSEARCH_HOSTS:-https://${dev_host}:9200}"

# Credentials are per service in this repo (WRITE_DATABASE_USER, READ_DATABASE_*, …).
# Reading a generic DATABASE_USER/PASSWORD silently falls back to postgres/postgres
# and then fails against any host that set its own passwords.
case "$service_name" in
    write-service|write-*)
        database_port="$write_database_port"
        database_name="${WRITE_DATABASE_NAME:-power_finance_write}"
        database_user="${WRITE_DATABASE_USER:-postgres}"
        database_password="${WRITE_DATABASE_PASSWORD:-postgres}"
        redis_port="$write_redis_port"
        ;;
    read-service|read-*)
        database_port="$read_database_port"
        database_name="${READ_DATABASE_NAME:-power_finance_read}"
        database_user="${READ_DATABASE_USER:-postgres}"
        database_password="${READ_DATABASE_PASSWORD:-postgres}"
        redis_port="$read_redis_port"
        ;;
    ai-service|ai-*)
        database_port="$ai_database_port"
        database_name="${AI_DATABASE_NAME:-power_finance_ai}"
        database_user="${AI_DATABASE_USER:-postgres}"
        database_password="${AI_DATABASE_PASSWORD:-postgres}"
        redis_port="$read_redis_port"
        ;;
    webhook-service)
        database_port="$webhook_database_port"
        database_name="${WEBHOOK_DATABASE_NAME:-power_finance_webhooks}"
        database_user="${WEBHOOK_DATABASE_USER:-postgres}"
        database_password="${WEBHOOK_DATABASE_PASSWORD:-postgres}"
        redis_port="$read_redis_port"
        ;;
    *)
        database_port="$write_database_port"
        database_name="${WRITE_DATABASE_NAME:-power_finance_write}"
        database_user="${WRITE_DATABASE_USER:-postgres}"
        database_password="${WRITE_DATABASE_PASSWORD:-postgres}"
        redis_port="$write_redis_port"
        ;;
esac

# ai-service and webhook-service read a whole URL rather than DATABASE_* parts.
service_specific_lines=""
case "$service_name" in
    ai-service|ai-*)
        service_specific_lines="AI_DATABASE_URL=postgresql+psycopg://${database_user}:${database_password}@${dev_host}:${database_port}/${database_name}
"
        ;;
    webhook-service)
        service_specific_lines="POSTGRES_DSN=postgres://${database_user}:${database_password}@${dev_host}:${database_port}/${database_name}
"
        ;;
esac

mkdir -p "$(dirname "$output_file")"
cat > "$output_file" <<ENVEOF
# Generated by \`make sandbox-env NAME=$sandbox_name SERVICE=$service_name\`.
# Source this before running $service_name natively against the shared baseline.
# Every endpoint points at the dev host; nothing here starts infrastructure.
SANDBOX_ID=$sandbox_name

KAFKA_BOOTSTRAP_SERVERS=${dev_host}:${kafka_port}

DATABASE_HOST=$dev_host
DATABASE_PORT=$database_port
DATABASE_NAME=$database_name
DATABASE_USER=$database_user
DATABASE_PASSWORD=$database_password

REDIS_HOST=$dev_host
REDIS_PORT=$redis_port

IMMUDB_HOST=$dev_host
IMMUDB_PORT=$immudb_port
IMMUDB_USER=${IMMUDB_USER:-immudb}
IMMUDB_PASSWORD=${IMMUDB_PASSWORD:-immudb}

$service_specific_lines
ELASTICSEARCH_HOSTS=$elasticsearch_hosts
ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD:-changeme}
ELASTICSEARCH_VERIFY_CERTS=${ELASTICSEARCH_VERIFY_CERTS:-false}

OTEL_EXPORTER_OTLP_ENDPOINT=http://${dev_host}:4317
OTEL_SERVICE_NAME=$service_name
OTEL_DEPLOYMENT_ENVIRONMENT=sandbox
ENVEOF

echo "$output_file"
