# Generated by Django 5.2.6 on 2026-03-10 07:34

import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import finances.domain.entities.expense_category
import uuid
from django.conf import settings
from django.db import migrations, models
from pathlib import Path
import json


def seed_currencies(apps, schema_editor):
    currency = apps.get_model("finances", "Currency")

    file_path = Path(__file__).resolve().parent / "data" / "currencies.json"

    with open(file_path) as f:
        data = json.load(f)

    currency.objects.bulk_create(
        [
            currency(
                code=c["code"],
                name=c["currency"],
                numeric=c["number"],
                digits=c["digits"],
            )
            for c in data
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('numeric', models.CharField(max_length=3)),
                ('digits', models.IntegerField()),
            ],
            options={
                'db_table': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('credit', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.currency')),
            ],
        ),
        migrations.RunPython(
            code=seed_currencies,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wallet',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RenameModel(
            old_name='Currency',
            new_name='CurrencyModel',
        ),
        migrations.RenameModel(
            old_name='Wallet',
            new_name='WalletModel',
        ),
        migrations.AlterModelTable(
            name='currencymodel',
            table='finances_currencies',
        ),
        migrations.AlterModelTable(
            name='walletmodel',
            table='finances_wallets',
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('send_amount', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('receive_amount', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer')])),
                ('category', models.CharField(choices=[('food', 'Food'), ('transportation', 'Transportation'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('other', 'Other'), ('health', 'Health'), ('education', 'Education'), ('travel', 'Travel'), ('bills', 'Bills')], default=finances.domain.entities.expense_category.ExpenseCategory['OTHER'])),
                ('receive_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive_wallet', to='finances.walletmodel')),
                ('send_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_wallet', to='finances.walletmodel')),
            ],
            options={
                'db_table': 'finances_transactions',
            },
        ),
    ]
