# Generated by Django 5.2.6 on 2026-03-25 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_webhookdeliverymodel_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventSubscriptionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('transaction.created', 'Transaction Created'), ('transaction.updated', 'Transaction Updated'), ('transaction.deleted', 'Transaction Deleted')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'finances_webhook_event_subscriptions',
            },
        ),
        migrations.RemoveIndex(
            model_name='webhookdeliverymodel',
            name='finances_we_event_t_9e3cfc_idx',
        ),
        migrations.RemoveField(
            model_name='webhookdeliverymodel',
            name='event_type',
        ),
        migrations.AddField(
            model_name='webhookeventsubscriptionmodel',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='finances.webhookendpointmodel'),
        ),
        migrations.AddIndex(
            model_name='webhookeventsubscriptionmodel',
            index=models.Index(fields=['endpoint'], name='finances_we_endpoin_93fc37_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookeventsubscriptionmodel',
            index=models.Index(fields=['event_type'], name='finances_we_event_t_46b9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookeventsubscriptionmodel',
            index=models.Index(fields=['endpoint', 'event_type'], name='finances_we_endpoin_af4038_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookeventsubscriptionmodel',
            constraint=models.UniqueConstraint(fields=('endpoint', 'event_type'), name='unique_webhook_subscription_endpoint_event_type'),
        ),
    ]
