# Generated by Django 5.2.6 on 2026-04-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_webhookpayloadmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookpayloadmodel',
            name='headers',
            field=models.JSONField(default=dict),
        ),
    ]
