apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: LoadBalancer
  # Routes to pods from django-deployment
  selector:
    app.kubernetes.io/name: django-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
