apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  # Routes to pods from postgres-deployment
  selector:
    app.kubernetes.io/name: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
