apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  # Routes to pods from rabbitmq-deployment
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    # AMQP port
    - protocol: TCP
      port: 5672
      targetPort: 5672
    # Management UI port
    - protocol: TCP
      port: 15672
      targetPort: 15672