# Generated by Django 5.2.14 on 2026-05-18 05:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('numeric', models.CharField(max_length=3)),
                ('digits', models.IntegerField()),
            ],
            options={
                'db_table': 'finances_currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OutboxEntryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(db_column='aggregatetype', max_length=64)),
                ('aggregate_id', models.CharField(db_column='aggregateid', max_length=64)),
                ('event_type', models.CharField(db_column='type', max_length=128)),
                ('payload', models.JSONField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'outbox_events',
                'indexes': [models.Index(fields=['aggregate_type', 'aggregate_id'], name='outbox_even_aggrega_374270_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_write_core.currencymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finances_wallets',
            },
        ),
    ]
