# Generated by Django 5.2.14 on 2026-06-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_write_core', '0003_outbox_bigint_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxentrymodel',
            name='partition_key',
            field=models.CharField(db_column='partitionkey', default='', max_length=64),
        ),
    ]
