# Generated by Django 5.2.14 on 2026-06-12 22:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_write_core', '0005_notificationmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('secret', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'webhooks',
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscriptionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='data_write_core.webhookmodel')),
            ],
            options={
                'db_table': 'webhook_subscriptions',
            },
        ),
        migrations.AddIndex(
            model_name='webhookmodel',
            index=models.Index(fields=['user', '-created_at'], name='webhooks_user_id_0fd59a_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhooksubscriptionmodel',
            constraint=models.UniqueConstraint(fields=('webhook', 'event_type'), name='uniq_webhook_event_type'),
        ),
    ]
