# Generated by Django 5.2.14 on 2026-08-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_write_core', '0006_webhookmodel_webhooksubscriptionmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletmodel',
            name='category',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='zero_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
