# Generated by Django 5.2.14 on 2026-08-22 20:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_write_core', '0008_transactionchainmodel_transactionmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='data_write_core.walletmodel'),
        ),
        migrations.CreateModel(
            name='GoalModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('target', models.DecimalField(decimal_places=2, max_digits=20)),
                ('finish_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_write_core.currencymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finances_goals',
            },
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='data_write_core.goalmodel'),
        ),
        migrations.AddIndex(
            model_name='transactionmodel',
            index=models.Index(fields=['goal', '-created_at'], name='ft_goal_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('goal__isnull', True), ('wallet__isnull', False)), models.Q(('goal__isnull', False), ('wallet__isnull', True)), _connector='OR'), name='ft_exactly_one_container'),
        ),
        migrations.AddIndex(
            model_name='goalmodel',
            index=models.Index(fields=['user', '-created_at', '-id'], name='fg_user_keyset_idx'),
        ),
    ]
