# Generated by Django 5.2.14 on 2026-09-01 06:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_write_core', '0011_notification_target_shape'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_external_id', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(max_length=16)),
                ('kind', models.CharField(max_length=64)),
                ('severity', models.CharField(default='info', max_length=16)),
                ('severity_rank', models.IntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True, default='')),
                ('subject_type', models.CharField(blank=True, default='', max_length=32)),
                ('subject_id', models.CharField(blank=True, default='', max_length=64)),
                ('money_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('money_currency', models.CharField(blank=True, default='', max_length=8)),
                ('group_key', models.CharField(blank=True, default='', max_length=128)),
                ('occurrences', models.IntegerField(default=1)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_id', models.CharField(blank=True, default='', max_length=64)),
                ('resolutions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'actions',
                'indexes': [models.Index(fields=['user', 'status'], name='action_user_status_idx'), models.Index(fields=['expires_at'], name='action_expiry_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending'), models.Q(('group_key', ''), _negated=True)), fields=('user', 'group_key'), name='action_one_pending_per_group')],
            },
        ),
    ]
