# Generated by Django 5.2.14 on 2026-09-01 08:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_write_core', '0012_actionmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_external_id', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('trigger_type', models.CharField(max_length=16)),
                ('trigger_event', models.CharField(blank=True, default='', max_length=32)),
                ('trigger_schedule', models.CharField(blank=True, default='', max_length=16)),
                ('filter_body', models.JSONField(blank=True, null=True)),
                ('effects', models.JSONField(default=list)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('runs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'automations',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True), ('enabled', True)), fields=['user', 'created_at'], name='automation_live_idx'), models.Index(fields=['user', 'enabled'], name='automation_user_enabled_idx')],
            },
        ),
    ]
