# Generated by Django 5.2.14 on 2026-09-02 00:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_write_core', '0013_automationmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRunModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_key', models.CharField(max_length=128)),
                ('ran_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs_made', to='data_write_core.automationmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'automation_runs',
                'indexes': [models.Index(fields=['user', 'ran_at'], name='automation_run_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('automation', 'run_key'), name='automation_run_once_per_key')],
            },
        ),
    ]
