# Generated by Django 5.2.14 on 2026-09-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_write_core', '0014_automationrunmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookmodel',
            name='previous_secret',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='webhookmodel',
            name='previous_secret_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookmodel',
            name='previous_secret_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookmodel',
            name='secret_version',
            field=models.IntegerField(default=1),
        ),
    ]
