syntax = "proto3";

package power_finance.events.v1;

option go_package = "github.com/power-finance/kafka-messages-proto/generated/go/events/v1;eventsv1";
option java_package = "com.powerfinance.events.v1";
option java_multiple_files = true;
option java_outer_classname = "GoalProto";

import "google/protobuf/timestamp.proto";


message GoalCreated {
  string event_id = 1;
  google.protobuf.Timestamp occurred_at = 2;
  int32 schema_version = 3;

  string goal_id = 10;
  int32 user_id = 11;
  string title = 12;
  string currency_code = 13;
  string target = 14;

  google.protobuf.Timestamp created_at = 15;
  google.protobuf.Timestamp finish_at = 16;
  string url = 17;
}

message GoalUpdated {
  string event_id = 1;
  google.protobuf.Timestamp occurred_at = 2;
  int32 schema_version = 3;

  string goal_id = 10;
  int32 user_id = 11;
  string previous_title = 12;
  string new_title = 13;

  google.protobuf.Timestamp updated_at = 14;

  string target = 15;
  google.protobuf.Timestamp finish_at = 16;
  string url = 17;
}

message GoalDeleted {
  string event_id = 1;
  google.protobuf.Timestamp occurred_at = 2;
  int32 schema_version = 3;

  string goal_id = 10;
  int32 user_id = 11;

  google.protobuf.Timestamp deleted_at = 12;
}
