syntax = "proto3";

package power_finance.events.v1;

option go_package = "github.com/power-finance/kafka-messages-proto/generated/go/events/v1;eventsv1";
option java_package = "com.powerfinance.events.v1";
option java_multiple_files = true;
option java_outer_classname = "NotificationProto";

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";


message NotificationRequested {
  string event_id = 1;
  google.protobuf.Timestamp occurred_at = 2;
  int32 schema_version = 3;

  int32 user_id = 10;
  string user_external_id = 11;
  string short = 12;
  string message = 13;
  google.protobuf.Struct payload = 14;
}

message NotificationCreated {
  string event_id = 1;
  google.protobuf.Timestamp occurred_at = 2;
  int32 schema_version = 3;

  string notification_id = 10;
  int32 user_id = 11;
  string short = 12;
  string message = 13;
  google.protobuf.Struct payload = 14;
  google.protobuf.Timestamp created_at = 15;
}

message NotificationsAcknowledged {
  string event_id = 1;
  google.protobuf.Timestamp occurred_at = 2;
  int32 schema_version = 3;

  repeated string notification_ids = 10;
  int32 user_id = 11;
  google.protobuf.Timestamp acknowledged_at = 12;
}

message NotificationDeleted {
  string event_id = 1;
  google.protobuf.Timestamp occurred_at = 2;
  int32 schema_version = 3;

  string notification_id = 10;
  int32 user_id = 11;
  google.protobuf.Timestamp deleted_at = 12;
}
