ENVIRONMENT_VARIABLE_SERVICE_NAME = "OTEL_SERVICE_NAME"
ENVIRONMENT_VARIABLE_EXPORTER_ENDPOINT = "OTEL_EXPORTER_OTLP_ENDPOINT"
ENVIRONMENT_VARIABLE_SDK_DISABLED = "OTEL_SDK_DISABLED"
ENVIRONMENT_VARIABLE_SAMPLER_RATIO = "OTEL_TRACES_SAMPLER_ARG"
ENVIRONMENT_VARIABLE_DEPLOYMENT_ENVIRONMENT = "OTEL_DEPLOYMENT_ENVIRONMENT"

DEFAULT_EXPORTER_ENDPOINT = "http://localhost:4317"
DEFAULT_SAMPLER_RATIO = 1.0
DEFAULT_DEPLOYMENT_ENVIRONMENT = "development"
