/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.gradleup.shadow") version "9.0.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    compileOnly(libs.flink.streaming)
    compileOnly(libs.flink.clients)
    compileOnly(libs.flink.connector.base)

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.flink.streaming)
    testImplementation(libs.flink.clients)

    // Flink operator test harness for driving keyed-state functions in tests.
    testImplementation("org.apache.flink:flink-test-utils:2.0.0")
    testImplementation("org.apache.flink:flink-streaming-java:2.0.0:tests")
    testImplementation("org.apache.flink:flink-runtime:2.0.0:tests")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.flink.connector.kafka)
    // protobuf runtime for the generated event bindings — must ship in the fat jar.
    implementation(libs.protobuf.java)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.powerfinance.antifraud.App"
}

// Consume the committed Java bindings from the shared proto library as source.
sourceSets {
    main {
        java {
            srcDir("../../../libraries/kafka-messages-proto/generated/java")
        }
    }
}

// Flink core is compileOnly (kept out of the fat jar), so add it back for local `run`.
tasks.named<JavaExec>("run") {
    classpath += configurations.compileOnly.get()
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
