from django.urls import path

from .views.actions import ActionResolveView
from .views.fallback_read import (
    FallbackGoalListView,
    FallbackGoalResourceView,
    FallbackNotificationListView,
    FallbackNotificationResourceView,
    FallbackTransactionListView,
    FallbackTransactionResourceView,
    FallbackWalletListView,
    FallbackWalletResourceView,
    FallbackWebhookEventListView,
    FallbackWebhookListView,
    FallbackWebhookResourceView,
)
from .views.goals import GoalListView, GoalResourceView
from .views.notifications import (
    NotificationAckView,
    NotificationBatchAckView,
    NotificationResourceView,
)
from .views.transaction_chains import (
    TransactionChainListView,
    TransactionChainResourceView,
)
from .views.transactions import (
    TransactionAdjustView,
    TransactionListView,
    TransactionResourceView,
)
from .views.wallets import WalletListView, WalletResourceView
from .views.webhooks import (
    WebhookEventListView,
    WebhookEventResourceView,
    WebhookListView,
    WebhookResourceView,
    WebhookSecretView,
)

urlpatterns = [
    path(
        "actions/<uuid:action_id>/resolve",
        ActionResolveView.as_view(),
        name="actions-resolve",
    ),
    path(
        "webhooks",
        WebhookListView.as_view(),
        name="webhooks-list",
    ),
    path(
        "webhooks/<uuid:webhook_id>",
        WebhookResourceView.as_view(),
        name="webhooks-resource",
    ),
    path(
        "webhooks/<uuid:webhook_id>/secret",
        WebhookSecretView.as_view(),
        name="webhooks-secret",
    ),
    path(
        "webhooks/<uuid:webhook_id>/events",
        WebhookEventListView.as_view(),
        name="webhooks-event-list",
    ),
    path(
        "webhooks/<uuid:webhook_id>/events/<uuid:subscription_id>",
        WebhookEventResourceView.as_view(),
        name="webhooks-event-resource",
    ),
    path(
        "notifications/ack",
        NotificationBatchAckView.as_view(),
        name="notifications-batch-ack",
    ),
    path(
        "notifications/<uuid:notification_id>/ack",
        NotificationAckView.as_view(),
        name="notifications-ack",
    ),
    path(
        "notifications/<uuid:notification_id>",
        NotificationResourceView.as_view(),
        name="notifications-resource",
    ),
    path(
        "transactions",
        TransactionListView.as_view(),
        name="transactions-list",
    ),
    path(
        "transactions/chains",
        TransactionChainListView.as_view(),
        name="transaction-chains-list",
    ),
    path(
        "transactions/chains/<uuid:chain_id>",
        TransactionChainResourceView.as_view(),
        name="transaction-chains-resource",
    ),
    path(
        "transactions/<uuid:transaction_id>",
        TransactionResourceView.as_view(),
        name="transactions-resource",
    ),
    path(
        "transactions/<uuid:transaction_id>/adjust",
        TransactionAdjustView.as_view(),
        name="transactions-adjust",
    ),
    path(
        "goals",
        GoalListView.as_view(),
        name="goals-list",
    ),
    path(
        "goals/<uuid:goal_id>",
        GoalResourceView.as_view(),
        name="goals-resource",
    ),
    path(
        "fallback-reads/goals",
        FallbackGoalListView.as_view(),
        name="fallback-goals-list",
    ),
    path(
        "fallback-reads/goals/<uuid:goal_id>",
        FallbackGoalResourceView.as_view(),
        name="fallback-goals-resource",
    ),
    path(
        "wallets",
        WalletListView.as_view(),
        name="wallets-list",
    ),
    path(
        "wallets/<uuid:wallet_id>",
        WalletResourceView.as_view(),
        name="wallets-resource",
    ),
    path(
        "fallback-reads/wallets",
        FallbackWalletListView.as_view(),
        name="fallback-wallets-list",
    ),
    path(
        "fallback-reads/wallets/<uuid:wallet_id>",
        FallbackWalletResourceView.as_view(),
        name="fallback-wallets-resource",
    ),
    path(
        "fallback-reads/transactions",
        FallbackTransactionListView.as_view(),
        name="fallback-transactions-list",
    ),
    path(
        "fallback-reads/transactions/<uuid:transaction_id>",
        FallbackTransactionResourceView.as_view(),
        name="fallback-transactions-resource",
    ),
    path(
        "fallback-reads/webhooks",
        FallbackWebhookListView.as_view(),
        name="fallback-webhooks-list",
    ),
    path(
        "fallback-reads/webhooks/<uuid:webhook_id>",
        FallbackWebhookResourceView.as_view(),
        name="fallback-webhooks-resource",
    ),
    path(
        "fallback-reads/webhooks/<uuid:webhook_id>/events",
        FallbackWebhookEventListView.as_view(),
        name="fallback-webhooks-event-list",
    ),
    path(
        "fallback-reads/notifications",
        FallbackNotificationListView.as_view(),
        name="fallback-notifications-list",
    ),
    path(
        "fallback-reads/notifications/<uuid:notification_id>",
        FallbackNotificationResourceView.as_view(),
        name="fallback-notifications-resource",
    ),
]
