from django.conf import settings
from observability import SANDBOX_HTTP_HEADER_NAME

DEFAULT_CORRELATION_HEADER_NAME = "X-Correlation-ID"
DEFAULT_SANDBOX_HEADER_NAME = SANDBOX_HTTP_HEADER_NAME

SETTING_NAME_CORRELATION_HEADER = "CORRELATION_ID_HEADER"
SETTING_NAME_SANDBOX_HEADER = "SANDBOX_ID_HEADER"

DEFAULT_HEADER_NAME = DEFAULT_CORRELATION_HEADER_NAME
SETTING_NAME = SETTING_NAME_CORRELATION_HEADER


def resolve_header_name() -> str:
    return getattr(
        settings,
        SETTING_NAME_CORRELATION_HEADER,
        DEFAULT_CORRELATION_HEADER_NAME,
    )


def resolve_sandbox_header_name() -> str:
    return getattr(
        settings,
        SETTING_NAME_SANDBOX_HEADER,
        DEFAULT_SANDBOX_HEADER_NAME,
    )
