from .automations_mapping import AUTOMATIONS_INDEX, AUTOMATIONS_MAPPING
from .goals_mapping import GOALS_INDEX, GOALS_MAPPING
from .transactions_mapping import TRANSACTIONS_INDEX, TRANSACTIONS_MAPPING
from .wallets_mapping import WALLETS_INDEX, WALLETS_MAPPING

INDEX_DEFINITIONS: dict[str, dict] = {
    WALLETS_INDEX: WALLETS_MAPPING,
    TRANSACTIONS_INDEX: TRANSACTIONS_MAPPING,
    AUTOMATIONS_INDEX: AUTOMATIONS_MAPPING,
    GOALS_INDEX: GOALS_MAPPING,
}
