apiVersion: v1
kind: ServiceAccount
metadata:
  name: immudb-sa
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: immudb-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["immudb-secrets"]
  verbs: ["get"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: immudb-rolebinding
subjects:
- kind: ServiceAccount
  name: immudb-sa
roleRef:
  kind: Role
  name: immudb-role
  apiGroup: rbac.authorization.k8s.io
