"""assistant messages

Revision ID: 3241f96ca480
Revises: e52fe8499a10
Create Date: 2026-09-02 04:04:14.759825
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3241f96ca480'
down_revision: str | None = 'e52fe8499a10'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_assistant_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ai_assistant_messages_feed_idx', 'ai_assistant_messages', ['external_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ai_assistant_messages_feed_idx', table_name='ai_assistant_messages')
    op.drop_table('ai_assistant_messages')
    # ### end Alembic commands ###
