"""projected transactions, accounts and entries

Revision ID: 978c45f7e58a
Revises: 
Create Date: 2026-08-25 21:42:37.077000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '978c45f7e58a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group', 'name', name='ai_accounts_identity')
    )
    op.create_index(op.f('ix_ai_accounts_user_id'), 'ai_accounts', ['user_id'], unique=False)
    op.create_table('ai_projected_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Uuid(), nullable=False),
    sa.Column('container_kind', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('evidence_url', sa.String(length=2048), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('chain_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_seq', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_projected_transactions_user_id'), 'ai_projected_transactions', ['user_id'], unique=False)
    op.create_table('ai_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('debit', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ai_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['ai_projected_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ai_entries_account_keyset', 'ai_entries', ['account_id', 'created_at', 'id'], unique=False)
    op.create_index('ai_entries_transaction', 'ai_entries', ['transaction_id', 'position'], unique=False)
    op.create_index(op.f('ix_ai_entries_user_id'), 'ai_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_entries_user_id'), table_name='ai_entries')
    op.drop_index('ai_entries_transaction', table_name='ai_entries')
    op.drop_index('ai_entries_account_keyset', table_name='ai_entries')
    op.drop_table('ai_entries')
    op.drop_index(op.f('ix_ai_projected_transactions_user_id'), table_name='ai_projected_transactions')
    op.drop_table('ai_projected_transactions')
    op.drop_index(op.f('ix_ai_accounts_user_id'), table_name='ai_accounts')
    op.drop_table('ai_accounts')
    # ### end Alembic commands ###
