apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  # Single node access — postgres does not support multi-node writes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi