apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  # Single node access — redis does not support multi-node writes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
