# Generated by Django 5.2.6 on 2026-03-07 01:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('numeric', models.CharField(max_length=3)),
                ('digits', models.IntegerField()),
            ],
            options={
                'db_table': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('credit', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='balance_management.currency')),
            ],
        ),
    ]
