# Generated by Django 5.2.6 on 2026-03-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_management', '0004_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
