# Generated by Django 5.2.6 on 2026-03-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_management', '0005_alter_wallet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
