# Generated by Django 5.2.6 on 2026-03-08 21:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_management', '0006_wallet_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('from_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_wallet', to='balance_management.wallet')),
                ('to_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_wallet', to='balance_management.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLadderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance_management.wallet')),
            ],
        ),
    ]
