# Generated by Django 5.2.6 on 2026-03-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_management', '0007_transaction_transactionladderentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transportation', 'Transportation'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('other', 'Other'), ('health', 'Health'), ('education', 'Education'), ('travel', 'Travel'), ('bills', 'Bills')], default='other'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('expense', 'Expense'), ('income', 'Income'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer')], null=True),
        ),
        migrations.DeleteModel(
            name='TransactionLadderEntry',
        ),
    ]
