apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  # Single node access — rabbitmq clustering requires separate peer discovery setup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
